"""create_stays_and_consumptions

Revision ID: 6a12a4c28283
Revises: 8e33283d993a
Create Date: 2026-03-05 19:36:18.307813

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6a12a4c28283"
down_revision: Union[str, Sequence[str], None] = "8e33283d993a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stays",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("room_id", sa.UUID(), nullable=False),
        sa.Column("guest_name", sa.String(), nullable=False),
        sa.Column("check_in", sa.DateTime(), nullable=False),
        sa.Column("check_out", sa.DateTime(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("total_amount", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["room_id"],
            ["rooms.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_stays_id"), "stays", ["id"], unique=False)
    op.create_table(
        "consumptions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("stay_id", sa.UUID(), nullable=False),
        sa.Column("item_name", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["stay_id"],
            ["stays.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_consumptions_id"), "consumptions", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_consumptions_id"), table_name="consumptions")
    op.drop_table("consumptions")
    op.drop_index(op.f("ix_stays_id"), table_name="stays")
    op.drop_table("stays")
    # ### end Alembic commands ###
